create or replace function CK_SALE_SF(
P_ID BB_PRODUCT.IDPRODUCT%TYPE,
P_DATE BB_PRODUCT.SALEEND%TYPE
)
RETURN varchar2
IS
NV_START bb_product.salestart%TYPE;
NV_END bb_product.saleend%TYPE;
BEGIN
SELECT SALESTART,SALEEND INTO NV_START,NV_END FROM BB_PRODUCT WHERE IDPRODUCT=P_ID;
IF(P_DATE>=NV_START AND P_DATE<=NV_END) THEN
RETURN 'TRUE';
ELSE
RETURN 'FALSE';
END IF;
END;
