SELECT * FROM BB_BASKETITEM;
DELETE FROM BB_BASKETITEM WHERE IDBASKETITEM=50;
SELECT * FROM BB_BASKETSTATUS;
DELETE FROM BB_BASKETSTATUS WHERE IDSTATUS=36;
SELECT * FROM BB_PRODUCT;
DELETE FROM BB_PRODUCT WHERE IDPRODUCT=12;
COMMIT;