CREATE OR REPLACE PROCEDURE PROD_ADD_SP(
P_ID bb_product.idproduct%TYPE,
P_NAME bb_product.productname%TYPE,
P_DESCRIPTION bb_product.description%TYPE,
P_IMAGE bb_product.productimage%TYPE,
P_PRICE bb_product.price%TYPE,
P_STATUS bb_product.active%TYPE
)
IS
BEGIN
INSERT INTO BB_PRODUCT(IDPRODUCT,PRODUCTNAME,DESCRIPTION,PRODUCTIMAGE,PRICE,ACTIVE) 
VALUES(
P_ID,P_NAME,P_DESCRIPTION,P_IMAGE,P_PRICE,P_STATUS
);
COMMIT;
END PROD_ADD_SP;