
CREATE OR REPLACE PROCEDURE SP_UPDATE_PRODUCT(
P_IDPRODUCT BB_PRODUCT.IDPRODUCT%TYPE,
P_DESCRIPTION BB_PRODUCT.DESCRIPTION%TYPE
)
IS
BEGIN
UPDATE BB_PRODUCT SET DESCRIPTION=P_DESCRIPTION WHERE IDPRODUCT=P_IDPRODUCT;
END SP_UPDATE_PRODUCT;