create or replace function TAX_COST_SP(
P_STATE IN BB_TAX.STATE%TYPE,
P_SUBTOTAL IN BB_BASKET.SUBTOTAL%TYPE
)
return NUMBER
IS
BEGIN
IF P_STATE='VA' THEN
RETURN P_SUBTOTAL*0.045;
ELSIF P_STATE='NC' THEN
RETURN P_SUBTOTAL*0.03;
ELSIF P_STATE='SC' THEN
RETURN P_SUBTOTAL*0.06;
END IF;
END TAX_COST_SP;
